export const sliderSetting={
    spaceBetween:50,
    slidesPerView:3,
    breakpoints:{
        380:{
            slidesPerView:1
        },
        480:{
            slidesPerView:1
        },
        600:{
            slidesPerView:2
        },
        750:{
            slidesPerView:3
        },
        1100:{
            slidesPerView:4
        }
    }
}